### ISSUE TITLE
Proposal for maintainership

### ISSUE THREAD

**Issue by milouse** [slim-template/emacs-slim#22]
Hi,

As a long time slim and emacs user, I’d like to propose my candidature as a new co-maintainer for this package. Along with reviewing pending MR and issues and watching for new ones, I’d like to make a new release and propose this package in the new nongnu elpa repository.

Have a great day.

**Comment by minad** [comment]
Thanks! Do you already maintain other Emacs packages or ELPA or MELPA?

**Comment by milouse** [comment]
Yes, I’m the current maintainer of [flycheck-grammalecte](https://melpa.org/#/flycheck-grammalecte) (french grammar checker) and the [dracula color theme](https://elpa.nongnu.org/nongnu/dracula-theme.html).

**Comment by minad** [comment]
Thanks. I've invited you.

**Comment by milouse** [comment]
Thank you very much!
